# Generated by Django 3.2.3 on 2021-07-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='customer_name',
            new_name='supplier_name',
        ),
    ]
